export type SAMPLE_MODULE_FETCH = 'SAMPLE_MODULE_FETCH'
export const SAMPLE_MODULE_FETCH: SAMPLE_MODULE_FETCH = 'SAMPLE_MODULE_FETCH'

export type SAMPLE_MODULE_SET = 'SAMPLE_MODULE_SET'
export const SAMPLE_MODULE_SET: SAMPLE_MODULE_SET = 'SAMPLE_MODULE_SET'
